/*
  Warnings:

  - You are about to drop the column `token` on the `SetPasswordToken` table. All the data in the column will be lost.
  - Added the required column `tokenHash` to the `SetPasswordToken` table without a default value. This is not possible if the table is not empty.

*/
-- Delete all existing set-password tokens before migration (they are invalid without tokenHash)
-- This is safe because onboarding tokens are temporary and can be regenerated by managers
DELETE FROM "SetPasswordToken";

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_SetPasswordToken" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" DATETIME NOT NULL,
    CONSTRAINT "SetPasswordToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
-- No INSERT needed since we deleted all rows above
DROP TABLE "SetPasswordToken";
ALTER TABLE "new_SetPasswordToken" RENAME TO "SetPasswordToken";
CREATE UNIQUE INDEX "SetPasswordToken_userId_key" ON "SetPasswordToken"("userId");
CREATE UNIQUE INDEX "SetPasswordToken_tokenHash_key" ON "SetPasswordToken"("tokenHash");
CREATE INDEX "SetPasswordToken_tokenHash_idx" ON "SetPasswordToken"("tokenHash");
CREATE INDEX "SetPasswordToken_expiresAt_idx" ON "SetPasswordToken"("expiresAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;